debug: true

clone:
    path: hypriot/rpi-busybox-httpd

publish:
  docker:
    username: $$DOCKER_USER
    password: $$DOCKER_PASS
    email: $$DOCKER_EMAIL
    repo: hypriot/rpi-busybox-httpd
    tag: "0.4"
